# Generated by Django 6.0.4 on 2026-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
