# Generated by Django 6.0.5 on 2026-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='low_stock_limit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
