# Generated by Django 6.0.5 on 2026-05-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_address_company_contact_number_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
