# Generated by Django 6.0.5 on 2026-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadfollowuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowuphistory',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadfollowuphistory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
